### ISSUE TITLE
Auth Server

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#1]

**Comment by Medic1111** [comment]
# AUTH -SERVER

> In order to fulfill this epic, the following tasks must be completed:

- [x] Create Login Route
- [x] Create Register Route
- [x] Encrypt Password on Register
- [x] Decrypt Password on Login
- [x] Generate token on both Login and Register and send to Client
- [x] Validate Register:
- [x] 409 User Already Exists
- [x] 500 Server Side Error
- [x] 422 Invalid Credentials
- [x] Validate Login
- [x] 404 User not registered
- [x] 403 Wrong password
- [x] 422 Invalid Credentials
- [x] 500 Server side error
- [x] Create Token Validation Function
- [x] Set it to the side to validate CRUD 

---

- [ ] Incorporate DB to save New Users to register
- [ ] Incorporate DB to find a User on login
