### ISSUE TITLE
Jest: Server

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#13]
### Implementing Jest and Supertest to run assertions on the server:

---

- [x] Test Login Route
- [x] Test for all status code
- [x] Test for response structure
- [x] Test Register Route
- [x] Test for all status code
- [x] Test for response structure
