### ISSUE TITLE
Server/DB

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#14]
### TRANSACTIONS DATA

> Upon login/register, the user currently receives user information and a token. User also needs transaction hx pertinent to him/her to be rendered as soon as 200.

- [ ] Data Scientist to ensure correlation
- [ ] SQL Specialist to write query for such data
- [ ] BE Engineer to integrate query to pertinent routes
- [ ] BE Engineer to structure data received in format secured and relevant to Client
