### ISSUE TITLE
Client/ Auth Component

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#15]
### JSX/AXIOS

> To ensure proper integration and communication between client and server, BE needs the following from FE:

- [x] Structure Login
- [x] Structure Register
- [x] Add Axios and make the calls to `/login` and `/register`
- [x] Ensure response is appropriate
- [x] Expect predetermine status code to handle USER feedback

**Comment by Medic1111** [comment]
@cappreccia-swanson this task is complete 🙏🏼🥳

**Comment by cappreccia-swanson** [comment]
10-4
