### ISSUE TITLE
SERVER

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#38]
### SERVER TASKS FOR THE NEXT 3 HOURS

---

- [x] Confirm with FE Search Route is working as expected
- [x] Fix obj response to include more info about the user (current just username): Login/Register
- [x] File Structure for Search Route
- [x] Unit Test Search Route
- [x] Review Create route
- [x] Unit test Create Route
- [x] File Structure Create Route
- [x] Confirm with Client it works as expected
- [x] Review Update Route
- [x] Unit Test Update Route
- [x] File Structure Update Route
- [ ] Confirm with Client it works as expected
- [x] Unit Test VALIDATION route
- [x] It has already been confirmed it works on the client
- [x] If time allows, Help Client fix State issues (bug) with rendering cycle of `isAuth `
- [x] Communicate with client to ensure their Create and Update forms are sending proper info expected by database

**Comment by Medic1111** [comment]
@cappreccia-swanson One hour late from what my Goal was, but all tasks done besides meeting with the Front End to ensure all runs well =) This should be ready to be closed as soon as I get that meeting in =)

**Comment by cappreccia-swanson** [comment]
Good stuff!! I'll be looking out for the meeting.
