### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#48]
> Update Read me:

- [ ] Project title
- [ ] Project brief description
- [ ] Project img/gif
- [ ] Award img
- [ ] live url specifying its the development demo
- [ ] list of tech stack
- [ ] How to Run it
- [ ] .env Example
- [ ] Contributors information
