### ISSUE TITLE
Client: Logout

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#50]
> Logout feature

- [ ] Create logout button
- [ ] Clear currentUser(state)
- [ ] Destroy token from local storage
- [ ] Redirect
