### ISSUE TITLE
Client: Update

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#53]
> Update feature

- [ ] Create component responsible for Update
- [ ] Create API call to appropriate route
- [ ] Check and confirm response is appropriate
- [ ] Ensure state gets updated and list reflects new status
